### ISSUE TITLE
.csproj

### ISSUE THREAD

**Issue by pavel-b-novikov** [AlexandrMMM/nsudotnet#1]
Большие задачи я не могу проверять в голове, как маленькие.
Их надо запускать (сюрприз!).
А вашу я запустить не могу, потому что нет .csproj-файла.

**Comment by AlexandrMMM** [comment]
Сейчас залью

**Comment by AlexandrMMM** [comment]
Финальное в DatabaseApp

**Comment by pavel-b-novikov** [comment]
ну отлично теперь. а где миграции-то? Мне как базу создавать?

**Comment by AlexandrMMM** [comment]
Добавил

**Comment by pavel-b-novikov** [comment]
а .csproj не закоммитил. А с добавлением existing-item-ов миграции явно в проект, приложение перестало собираться.

**Comment by AlexandrMMM** [comment]
Minakov.Nsudotnet.DatabaseApp - добавил .csproj проверил сборку, удалил лишнее - вроде бы собирается

**Comment by pavel-b-novikov** [comment]
... и снова нет
![image](https://cloud.githubusercontent.com/assets/2521412/7808778/81411450-03b7-11e5-9dea-49cb490763e7.png)

**Comment by AlexandrMMM** [comment]
201505260813112_ - там последние миграции такие

**Comment by pavel-b-novikov** [comment]
И что теперь? Я не могу Update-Database сделать из вашего солюшена, потому что он банально не собирается.

**Comment by AlexandrMMM** [comment]
Щас все ещё раз проверю и полностью перезалью в новую папку

**Comment by AlexandrMMM** [comment]
Minakov.Nsudotnet.DatabaseApp - закомитил, у меня на компьютере полностью собирается

**Comment by pavel-b-novikov** [comment]
... я вынужден вас расстроить
![image](https://cloud.githubusercontent.com/assets/2521412/7814681/77818dea-03e5-11e5-909e-703505c1ade7.png)

**Comment by AlexandrMMM** [comment]
Minakov.Nsudotnet.DatabaseApp - все повторно перепроверил и перезалил у меня вроде как создается, миграции пересоздал

**Comment by pavel-b-novikov** [comment]
На кой вы захардкодили строку подключения?

**Comment by AlexandrMMM** [comment]
ошибочка вышла, не убрал в Resources.ConnectionString - забыл

**Comment by pavel-b-novikov** [comment]
Зачем вы вызываете .CreateMap каждый раз заново? В документации разве не было сказано что маппинги создаются один раз?

**Comment by pavel-b-novikov** [comment]
Валидацию вы делаете вручную? А то есть создать отдельный контрол на создание/обновление отдельной сущности и использовать IDataErrorInfo - нет? 
Ну хорошо, про IDataErrorInfo я не рассказывал.
Но отдельный контрол-то на создание/обновление записи можно было сделать? 
ОО-декомпозиция? Не, не слышал.

**Comment by pavel-b-novikov** [comment]
Так же, судя по всему, вы не пользуетесь решарпером?

**Comment by AlexandrMMM** [comment]
Пользуюсь

**Comment by AlexandrMMM** [comment]
Да можно было создать всплавающие окно для создания и обновления записи и там исправлять данные а не так банально как сделано у меня, прописать это все в отдельной View и выводить окошко при нажатие соответствующей кнопки, но меня немного поджимали сроки и я не успел это вынести в отдельную сущность, также как и мапу не перенес в конструктор

**Comment by pavel-b-novikov** [comment]
это конечно шедеврально
![image](https://cloud.githubusercontent.com/assets/2521412/7815879/e6362eec-03ec-11e5-874d-3e1100036869.png)

**Comment by pavel-b-novikov** [comment]
Ладно, надо придумать что-то из дополнительных вопросов.
