### ISSUE TITLE
[DatabaseApp] Обновление списков

### ISSUE THREAD

**Issue by pavel-b-novikov** [AlexandrMMM/nsudotnet#2]
А вот я обратил внимание что вы используете обновление списков во многих местах системы. При том по кнопке. Ну т.е. надо явно нажать кнопку, чтобы содержимое списка обновилось.

Придумайте схему в рамках действующей архитектуры, чтобы эти списки обновлялись сами, если модифицируются те или иные сущности. И опишите на словах (реализовывать не надо).

**Comment by AlexandrMMM** [comment]
1)Тупо в лоб - прицепляем к TabControl cal:Message.Attach="Change" метод в котором вызываем изменение во всех существующих вкладках всех наших вспомогательных таблиц.
2)Смотрим какая вкладка выбрана с помощью SelectedIndex="{Binding SelectIndex}" и вызываем все рефрешы для этой вкладки в Change методе прикрепленном к TabControl и там меняем данные для конкретного элемента.

**Comment by AlexandrMMM** [comment]
А ещё можно все наши списки вынести в MainViewModel - при создание объекта определенного класса туда передаем все наши листы в качестве аргумента конструктора и при вызове NotifyOfpropertyChange(() => List) при изменение определенных сущностей, данный лист он будет изменяться,  а так как он во MainViewModel передается всем классам которым он нужен в конструкторе и он один, он будет менятся во всех наших ViewModel и там автоматически будут обновляться таблицы.

**Comment by AlexandrMMM** [comment]
Создаем класс A в котором мы можем изменить значение данного листа. в MainViewModel передаем в класс B в котором есть список с этими данными наш лист из класса A. При изменение Вызывается метод NotifyOfpropertyChange(() => лист) и лист сразу будет менятся во всех местах где он есть.

**Comment by pavel-b-novikov** [comment]
Т.е. вы будете добавлять по 2 новых класса на каждое место, где у вас редактируются все листы?

**Comment by AlexandrMMM** [comment]
Нет. У нас есть Property, например PersonalDataList в классе Sportsman и PersonalDataList в классе PersonalData - им мы будем давать значение некого списка _personalDataList созданного во MainViewModel. Один _personalDataList в MainViewModel  передается всем кому он нужен и там у каждого по своей NotifyOfpropertyChange(() => лист)  он будет обновляться. Список - один, Property у каждого свои.

**Comment by pavel-b-novikov** [comment]
> NotifyOfpropertyChange(() => лист)

Не сработает.

**Comment by AlexandrMMM** [comment]
Вроде работает, может я конечно не правильно свое задумку описываю. Ну то есть: у нас есть public IObservableCollection<PersonalDataViewModel> PersonalDataList { get; set; } в SportsmanGrudViewModel и такой же есть в PersonalDataGrudViewModel в конструкторе MainViewModel в качестве параметра мы передаем _personalDataList созданный в MainViewModel и передаем его классам. Там при add в PersonalDataGrudViewModel мы делаем NotifyOfPropertyChange(() => PersonalDataList); и обновляется наш список в первой сущности. Так как список изменился, об этом узнает список в SportsmanGrudViewModel и у нас идет его обновление.

**Comment by pavel-b-novikov** [comment]
А, ну то есть все на уровне ObservableColelction. 
Ну если вызывать .Referesh у самой коллекции - оно будет работать, ага.
Ток дело не в этом.
Это хорошо работает, когда у вас уже есть полный, на все приложение загруженный в MainViewModel список Observable-ов из БД. 
А когда у вас база в несколько ГБ и вытягивается из памяти постранично, это увы, не сработает.
Думаем дальше.

**Comment by AlexandrMMM** [comment]
То есть мне надо думать на счет того, как при вызове метода Add в PersonalDataGrudViewModel, делалось NotifyOfPropertyChange(() => PersonalDataList) не только для списка в нем но и для списка в SportsmanGrudViewModel?

**Comment by pavel-b-novikov** [comment]
Нет, вам надо подумать как перехватывать это на уровне логики

**Comment by AlexandrMMM** [comment]
Ну есть гипотеза создать некий кэш записей, который будет Observable - при обновлении или добавление или удаление записий мы будем вносить изменение в этом списке и всем, кто подписан на него будет приходить оповещение об изменениях, и они будут принимать эту информацию и обрабатывать так, как им надо

**Comment by pavel-b-novikov** [comment]
У вас EF-ные датасеты там. 
И еще раз - держите в голове, что IRL базы данных редко бывают маленькими.

**Comment by AlexandrMMM** [comment]
предположу что на уровне логики у нас должен возвращаться некоторый event который будет перехватываться на уровни UI и на основе которого будут производиться необходимые изменения

**Comment by pavel-b-novikov** [comment]
Правильное предположение.

**Comment by AlexandrMMM** [comment]
Скорее всего наш метод add должен будет иметь в качестве типа возвращаемого значения не void а не который Event который будет возвращаться, и перехватывться на уровень UI.

**Comment by pavel-b-novikov** [comment]
Очень странно. Ну и как это поможет?

**Comment by AlexandrMMM** [comment]
Предполагаю что надо создать в нашей реализации интерфейса логики некий ивент. при добавление мы должны будем сгенирировать данный эвент и вверху присвоить данному ивенту handler и в хендлере делать некоторые изменения с нашим списком при добавлении

**Comment by pavel-b-novikov** [comment]
Ну да. Как-то так. 
А стандартным синтаксисом C# тут можно обойтись?

**Comment by AlexandrMMM** [comment]
как я понимаю, да

**Comment by pavel-b-novikov** [comment]
Ну ладно. В целом ответ правильный. Пусть будет так.
